spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: jerry
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  file:
    name:  logs/blog-dev.log
    max-size: 10MB
    max-history: 1
  level:
    root : info
    codedrinker : debug
