spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog
    username: jerry
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
logging:
  file:
    name:  log/blog-pro.log
    max-size: 100MB
    max-history: 7
  level:
    root: warn
    codedrinker.blog: info
server:
  port: 8081
